# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Fourier Series
#'
#' Computes Fourier series required by Andrews curves.
#' @param mat Data matrix of size nxp
#' @param t Vector of size m where the series is being evaluated.
#' @param type Type of curve.
#' @return A nxm matrix where each row represents a curve.
#' @export
compute_fourier_series <- function(mat, t, type) {
    .Call(`_drewcurves_compute_fourier_series`, mat, t, type)
}

minmax <- function(mat) {
    .Call(`_drewcurves_minmax`, mat)
}

